name: Upload dotnet package

on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: WpfApp5/global.json

       
      - run: dotnet build --configuration Release Flarial.Launcher
      - name: Create the package
        run: dotnet pack --configuration Release Flarial.Launcher
     
