name: Upload dotnet package

on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: run
        run: |
            cd WpfApp5
            msbuild /m
